name: 'pkg-size'
description: 'Report npm package size on pull-requests'
author: 'Hiroki Osame <hiroki.osame@gmail.com>'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  build-command:
    description: 'Command to build the package with'
  work-directory: 
    description: where the build should run  
  dist-directory:
    description: where the dist folder is
  skip-npm-ci:
    description: 'Skip npm ci'
  comment-report:
    description: 'Whether to comment the build size report on the PR or not: true, false'
  mode:
    description: 'Report mode: regression (default), head-only'
  display-size:
    description: 'What size to display. Comma delimited list for multiple: uncompressed (default), gzip, brotli:'
  unchanged-files:
    description: 'Whether to show unchanged files: show, collapse, hide'
  sort-by:
    description: 'Which property to sort by: delta (size difference), headSize, baseSize, path'
  sort-order:
    description: 'Sort order: desc, asc'
  hide-files:
    description: 'Glob pattern to hide files with'
  pr-number:
    description: 'Number of the PR to work with'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
